name: Build and deploy Node.js app to Azure Web App - syunotice-frontend-server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout repository
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      # Step 3: Create .env file
      - name: Create .env file
        run: |
          echo REACT_APP_ADMIN_HC=${{ secrets.REACT_APP_ADMIN_HC }} >> .env
          echo REACT_APP_ADMIN_ID=${{ secrets.REACT_APP_ADMIN_ID }} >> .env
          echo REACT_APP_ADMIN_PW=${{ secrets.REACT_APP_ADMIN_PW }} >> .env
          echo REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }} >> .env
          echo REACT_APP_COOKIE=${{ secrets.REACT_APP_COOKIE }} >> .env
          echo REACT_APP_CRYPTO_KEY=${{ secrets.REACT_APP_CRYPTO_KEY }} >> .env
          echo NODE_ENV=production >> .env

      # Step 4: Install dependencies and build
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      # Step 5: Upload build folder as artifact
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: build-folder
          path: build/ # Only upload the build folder

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      # Step 1: Download the build folder artifact
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: build-folder

      # Step 2: Debug downloaded files
      - name: Debug downloaded files
        run: ls -R # Print the directory structure for debugging

      # Step 3: Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_317DCE6E11EC400EAE1D7E4BEFB515C7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E59489BE31BC47DB9D439200E2661BE4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9358F626040144239C33C5E2868CDDC3 }}

      # Step 4: Deploy the build folder to Azure Web App
      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: "syunotice-frontend-server"
          slot-name: "Production"
          package: ./build/ # Deploy only the build folder
